; https://www.php.net/manual/en/ini.core.php
expose_php = "0"
register_argc_argv = "0"
short_open_tag = "0"
zend.detect_unicode = "0"

; https://www.php.net/manual/en/apcu.configuration.php
apc.enable_cli = "1"

; https://www.php.net/manual/en/datetime.configuration.php
date.timezone = "UTC"

; https://www.php.net/manual/en/session.configuration.php
session.use_strict_mode = "1"

; https://symfony.com/doc/current/performance.html#configure-opcache-for-maximum-performance
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 20000
opcache.memory_consumption = 256

; https://symfony.com/doc/current/performance.html#configure-the-php-realpath-cache
realpath_cache_size = "4M"
realpath_cache_ttl = 600
